language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war

notifications:
  email:
    recipients:
      - amar.a@husky.neu.edu
      - patil.am@husky.neu.edu
      - patidar.p@husky.neu.edu
      - vishwanathan.a@husky.neu.edu   
